/**
 * Vercel Serverless Function — Knowledge Graph Save Proxy
 *
 * Uses SUPABASE_SERVICE_ROLE_KEY (server-side only) to bypass RLS.
 * The anon key on the client cannot INSERT/UPDATE/DELETE KG tables
 * because RLS policies restrict writes to service_role.
 *
 * Supported operations:
 *   POST /api/kg/save
 *   Body: { type: 'cuisine' | 'dish' | 'ingredient', data: {...} }
 *
 * Returns: { data: {...} } or { error: '...' }
 */

const TABLE_MAP = {
    cuisine:    'cuisines',
    dish:       'dishes',
    ingredient: 'ingredients',
}

export default async function handler(req, res) {
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' })
    }

    const supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL
    const serviceKey  = process.env.SUPABASE_SERVICE_ROLE_KEY

    if (!supabaseUrl || !serviceKey) {
        return res.status(500).json({
            error: 'SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY not configured on server',
        })
    }

    const { type, data } = req.body

    if (!type || !data) {
        return res.status(400).json({ error: 'type and data are required' })
    }

    const table = TABLE_MAP[type]
    if (!table) {
        return res.status(400).json({ error: `Unknown type: ${type}. Must be cuisine, dish, or ingredient` })
    }

    // Clean data — only send fields that exist in DB schema
    const cleanedData = sanitize(type, data)

    try {
        const response = await fetch(`${supabaseUrl}/rest/v1/${table}`, {
            method: 'POST',
            headers: {
                'apikey':        serviceKey,
                'Authorization': `Bearer ${serviceKey}`,
                'Content-Type':  'application/json',
                'Prefer':        'return=representation',
            },
            body: JSON.stringify(cleanedData),
        })

        const result = await response.json()

        if (!response.ok) {
            const msg = result?.message || result?.error || `Supabase error ${response.status}`
            console.error(`[kg/save] Supabase insert error for ${table}:`, msg, result)
            return res.status(response.status).json({ error: msg, details: result })
        }

        const saved = Array.isArray(result) ? result[0] : result
        console.log(`[kg/save] ✓ Saved ${type}: "${saved?.name || 'unknown'}" (id: ${saved?.id})`)
        return res.status(200).json({ data: saved })

    } catch (err) {
        console.error('[kg/save] Unexpected error:', err.message)
        return res.status(500).json({ error: err.message })
    }
}

/**
 * Only include fields that exist in the DB schema.
 * slug is auto-generated by a DB trigger (not sent).
 * cuisine_id requires a lookup — omit for now, cuisine_name is stored as text.
 */
function sanitize(type, data) {
    if (type === 'cuisine') {
        const {
            name, description, region, flavor_profile,
            aliases, typical_dishes, key_ingredients,
        } = data
        return clean({
            name, description, region, flavor_profile,
            aliases:         toArray(aliases),
            typical_dishes:  toArray(typical_dishes),
            key_ingredients: toArray(key_ingredients),
        })
    }
    if (type === 'dish') {
        const {
            name, cuisine_name, description,
            ingredients, preparation_style,
            dietary_tags, flavor_notes, best_pairing,
        } = data
        return clean({
            name, cuisine_name, description,
            ingredients:       toArray(ingredients),
            preparation_style, flavor_notes, best_pairing,
            dietary_tags:      toArray(dietary_tags),
        })
    }
    if (type === 'ingredient') {
        const {
            name, category, description, flavor_profile,
            common_pairings, dietary_info, season,
        } = data
        // Map category values AI uses → DB CHECK constraint values
        const CAT_MAP = {
            oil: 'other', sauce: 'other', grain: 'grain',
            protein: 'meat', dairy: 'dairy', fruit: 'fruit',
            vegetable: 'vegetable', spice: 'spice', herb: 'herb',
        }
        const mappedCategory = CAT_MAP[category?.toLowerCase()] || 'other'
        return clean({
            name, description, flavor_profile,
            category:        mappedCategory,
            common_pairings: toArray(common_pairings),
            dietary_info:    toArray(dietary_info),
            season:          season || null,
        })
    }
    return data
}

/** Ensure value is always an array (AI sometimes returns a comma-string) */
function toArray(val) {
    if (!val) return []
    if (Array.isArray(val)) return val
    if (typeof val === 'string') return val.split(',').map(s => s.trim()).filter(Boolean)
    return []
}

/** Remove undefined/null keys */
function clean(obj) {
    return Object.fromEntries(Object.entries(obj).filter(([, v]) => v !== undefined && v !== null))
}
