-- ═══════════════════════════════════════════════════════════════
-- GastroMap — Seed: 12 venues (Krakow + Warsaw)
-- Run after 001_locations.sql
-- ═══════════════════════════════════════════════════════════════

insert into public.locations (
    id, title, description, address, city, country, lat, lng,
    category, cuisine, image, rating, price_level, opening_hours,
    tags, special_labels, vibe, features, best_for, dietary,
    has_wifi, has_outdoor_seating, reservations_required,
    michelin_stars, michelin_bib,
    insider_tip, what_to_try, ai_keywords, ai_context
) values

-- ── KRAKOW ──────────────────────────────────────────────────────────────────

(
    '00000000-0000-0000-0000-000000000005',
    'Alchemia',
    'Iconic bohemian bar in Kazimierz with gothic candlelit interior and live music.',
    'ul. Estery 5, 31-056 Kraków',
    'Krakow', 'Poland',
    50.0503, 19.9487,
    'Bar', 'Polish',
    'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?q=80&w=1000&auto=format&fit=crop',
    4.5, '$', '10:00 - 03:00',
    ARRAY['Bohemian','Live Music','Gothic'],
    ARRAY['Live Music Venue','Cash Only'],
    ARRAY['Bohemian','Alternative','Energetic'],
    ARRAY['Live Music','Cash Only'],
    ARRAY['friends','party','date','after work'],
    ARRAY['vegetarian options'],
    false, false, false, 0, false,
    'There is a hidden room behind the wardrobe at the back — push it open. The secret back room is where locals hang out after midnight.',
    ARRAY['Żywiec beer on tap','Mulled wine in winter','House-made pierogi','Nalewka (Polish herbal liqueur)'],
    ARRAY['bohemian bar','gothic interior','live music krakow','alternative krakow','kazimierz nightlife','student bar','secret room','hidden door','candlelit bar','authentic local bar','late night krakow','cult bar'],
    'The most iconic bar in Kazimierz. Bohemian, dark, full of candles and mismatched furniture. A Krakow institution loved by locals and artists. Live music (jazz, blues, folk) most nights. Secret back room adds mystery. Cash only — very budget friendly.'
),
(
    '00000000-0000-0000-0000-000000000006',
    'Café Mleczarnia',
    'Pre-war Jewish atmosphere cafe-bar with a beautiful courtyard garden in Kazimierz.',
    'ul. Meiselsa 20, 31-058 Kraków',
    'Krakow', 'Poland',
    50.0519, 19.9438,
    'Cafe', 'Polish',
    'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=1000&auto=format&fit=crop',
    4.4, '$', '09:00 - 23:00',
    ARRAY['Vintage','Beer Garden','Kazimierz'],
    ARRAY['Hidden Courtyard','Historic Venue'],
    ARRAY['Bohemian','Cozy','Romantic'],
    ARRAY['Outdoor Seating','Beer Garden'],
    ARRAY['date','solo','friends'],
    ARRAY['vegetarian'],
    true, true, false, 0, false,
    'Ask for the hidden courtyard garden — it is one of the most romantic spots in all of Kazimierz. In summer it fills up fast, arrive by 18:00 to get a garden table.',
    ARRAY['Żurek soup','Craft beer on tap','Sernik (Polish cheesecake)','Mulled wine in winter'],
    ARRAY['kazimierz hidden gem','jewish quarter','pre-war atmosphere','romantic cafe','beer garden krakow','vintage interior','slow brunch','hipster krakow','courtyard cafe','instagrammable','lazy afternoon','local favourite'],
    'Beloved by Krakow locals for its authentic Kazimierz character. Pre-war Jewish district atmosphere with vintage decor. The courtyard garden is magical in summer. Perfect for long lazy afternoons with beer or coffee. Very budget-friendly.'
),
(
    '00000000-0000-0000-0000-000000000007',
    'Massolit Books & Café',
    'Cosy English-language bookshop and café — the best place to read, work, or just disappear.',
    'ul. Felicjanek 4, 31-034 Kraków',
    'Krakow', 'Poland',
    50.0581, 19.9328,
    'Cafe', 'International',
    'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?q=80&w=1000&auto=format&fit=crop',
    4.6, '$', '10:00 - 21:00',
    ARRAY['Books','Cozy','WiFi'],
    ARRAY['English Bookshop','Laptop Friendly'],
    ARRAY['Cozy','Quiet','Intellectual'],
    ARRAY['Books','WiFi','Board Games'],
    ARRAY['solo','date','freelancer'],
    ARRAY['vegetarian'],
    true, false, false, 0, false,
    'The deep sofa in the back room near the Shakespeare shelf is the best reading spot in Krakow. Claim it early on rainy days — it fills up by noon.',
    ARRAY['Filter coffee (single origin)','Homemade cakes','Quiche of the day','Tea selection'],
    ARRAY['bookshop cafe','english books','laptop friendly','reading cafe','quiet cafe krakow','freelancer spot','book lover','study cafe','rainy day krakow','cozy interior','remote work','intellectual crowd'],
    'The best bookshop-café in Krakow. Thousands of English-language books for sale, comfortable sofas, excellent coffee and cakes. Very quiet and relaxed. Loved by expats, students, and travellers. Perfect for long stays — no one rushes you.'
),
(
    '00000000-0000-0000-0000-000000000008',
    'Pierogi Mr. Vincent',
    'Van Gogh-themed pierogi restaurant in Kazimierz with over 30 creative varieties.',
    'ul. Bożego Ciała 12, 31-059 Kraków',
    'Krakow', 'Poland',
    50.0487, 19.9453,
    'Restaurant', 'Polish',
    'https://images.unsplash.com/photo-1559847844-5315695dadae?q=80&w=1000&auto=format&fit=crop',
    4.6, '$', '12:00 - 22:00',
    ARRAY['Pierogi','Polish','Kazimierz'],
    ARRAY['30+ Varieties','Vegetarian Friendly'],
    ARRAY['Casual','Quirky','Cozy'],
    ARRAY['Vegetarian Options','Takeaway'],
    ARRAY['family','friends','solo','lunch'],
    ARRAY['vegetarian','vegan options'],
    false, false, false, 0, false,
    'The Van Gogh Starry Night mural inside is worth a photo. Ask the staff about the off-menu "destroyed pierogi" — a kopytka-style variant that locals order.',
    ARRAY['Ruskie pierogi (potato & cheese)','Duck with cherry pierogi','Spinach & feta pierogi','Sweet strawberry dessert pierogi'],
    ARRAY['best pierogi krakow','pierogi restaurant','kazimierz food','polish dumplings','variety pierogi','vegetarian pierogi','lunch spot krakow','authentic polish food','tourist friendly','budget friendly','van gogh theme','creative pierogi'],
    'One of the best pierogi spots in Krakow. 30+ varieties from classic to creative. Great for first-timers wanting to try traditional Polish food. Van Gogh themed decor adds charm. Very affordable and filling. Vegetarians and vegans well catered for.'
),
(
    '00000000-0000-0000-0000-000000000009',
    'Plac Nowy – Zapiekanka Rotunda',
    'The legendary street food square in Kazimierz — home of the iconic Polish zapiekanka.',
    'Plac Nowy, 31-056 Kraków',
    'Krakow', 'Poland',
    50.0515, 19.9467,
    'Street Food', 'Polish',
    'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=1000&auto=format&fit=crop',
    4.4, '$', '10:00 - 03:00',
    ARRAY['Street Food','Market','Iconic'],
    ARRAY['Krakow Icon','Late Night'],
    ARRAY['Casual','Energetic','Bohemian'],
    ARRAY['Market','Outdoor Seating','Cash Only'],
    ARRAY['friends','groups','solo','late night'],
    ARRAY['vegetarian options'],
    false, true, false, 0, false,
    'Come after 22:00 when the nightlife crowd fills the square. Order at the Endzior stall (eastern side of the rotunda) — locally considered the best. Eat standing in the square with a cold beer from a nearby kiosk.',
    ARRAY['Classic zapiekanka (baguette, mushrooms, cheese)','Zapiekanka with jalapenos','Craft beer from kiosk'],
    ARRAY['zapiekanka','kazimierz square','street food krakow','budget food','late night food krakow','polish street food','flea market sunday','outdoor eating','iconic krakow','night market','cheap eats','must try krakow','local street food','plac nowy'],
    'Plac Nowy is the heart of Kazimierz nightlife. The zapiekanka (open-faced baguette with mushrooms, cheese, ketchup) is a Krakow institution — must try for any visitor. Flea market on Sunday mornings. Best atmosphere late at night. Very cheap and lively.'
),
(
    '00000000-0000-0000-0000-000000000010',
    'Bunkier Café',
    'Modernist glass café-bar that opens onto Planty Park — ideal for summer drinks.',
    'Plac Szczepański 3a, 31-011 Kraków',
    'Krakow', 'Poland',
    50.0629, 19.9364,
    'Bar', 'International',
    'https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=1000&auto=format&fit=crop',
    4.1, '$', '09:00 - 00:00',
    ARRAY['Park View','Modernist','Art Gallery'],
    ARRAY['Park Terrace','Art & Culture'],
    ARRAY['Artistic','Casual','Intellectual'],
    ARRAY['Outdoor Seating','Gallery','Park View'],
    ARRAY['date','solo','friends','after work'],
    ARRAY['vegetarian options'],
    true, true, false, 0, false,
    'In summer the full glass walls fold open completely — the bar merges with Planty park. Arrive around 18:00 for golden-hour drinks with the best park atmosphere.',
    ARRAY['Tank Żywiec beer','Fresh lemonade','Weekend brunch plate','Coffee with park view'],
    ARRAY['planty park view','modernist architecture','art gallery bar','cultural venue','summer drinks krakow','krakow old town bar','bunkier art','outdoor bar','dog friendly','after work drinks','architecture lover','gallery cafe'],
    'Part of the Bunkier Sztuki (Art Bunker) gallery. Unique modernist glass building right on Planty park. The best spot in Krakow for drinks with a park view. Casual and artsy crowd. Great for summer evenings. Often has vernissages and cultural events.'
),

-- ── WARSAW ──────────────────────────────────────────────────────────────────

(
    '00000000-0000-0000-0000-000000000011',
    'Hala Koszyki',
    'Beautifully restored 1908 Art Nouveau market hall with 18 food concepts under one roof.',
    'ul. Koszykowa 63, 00-667 Warszawa',
    'Warsaw', 'Poland',
    52.2234, 21.0082,
    'Food Hall', 'International',
    'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1000&auto=format&fit=crop',
    4.4, '$$', '07:00 - 23:00',
    ARRAY['Food Hall','Art Nouveau','Multiple Cuisines'],
    ARRAY['Historic Building','Warsaw Trendy'],
    ARRAY['Energetic','Casual','Trendy'],
    ARRAY['Multiple Concepts','WiFi','Outdoor Seating'],
    ARRAY['family','friends','groups','lunch','solo'],
    ARRAY['vegan','vegetarian','gluten-free options'],
    true, true, false, 0, false,
    'Visit Thursday–Sunday evenings when all 18 vendors are open and the hall is buzzing. The upper mezzanine has quieter seating with a beautiful view down into the main hall.',
    ARRAY['Bibimbap from Asian stand','Craft beer at the pub counter','Thai street food','Weekend brunch at any stall'],
    ARRAY['food hall warsaw','hala koszyki','Art Nouveau architecture','1908 building','multiple cuisines','trendy warsaw','srodmiescie','group dining','lunch warsaw','weekend brunch','international food','historic market hall','instagrammable interior','date ideas warsaw'],
    'The most beautiful food destination in Warsaw. A stunning 1908 Art Nouveau market hall, lovingly restored. 18 food concepts from sushi to craft beer. Great for groups where everyone wants something different. Lively and photogenic. Best experience Thu–Sun evening.'
),
(
    '00000000-0000-0000-0000-000000000012',
    'Bar Bambino',
    'Legendary communist-era milk bar open since 1957 — authentic cheap Polish canteen.',
    'ul. Krucza 21, 00-526 Warszawa',
    'Warsaw', 'Poland',
    52.2281, 21.0105,
    'Restaurant', 'Polish',
    'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?q=80&w=1000&auto=format&fit=crop',
    4.3, '$', '08:00 - 18:00',
    ARRAY['Milk Bar','Communist Era','Cheap'],
    ARRAY['Since 1957','Budget Icon'],
    ARRAY['Nostalgic','Casual','Local'],
    ARRAY['Cash Only','Budget'],
    ARRAY['solo','budget','lunch','local experience'],
    ARRAY['vegetarian options'],
    false, false, false, 0, false,
    'Pay first at the counter before collecting food. Come before 12:30 or after 13:30 to miss the office lunch rush. Closed weekends — weekday lunch only.',
    ARRAY['Bigos (hunter''s stew)','Kotlet schabowy (pork cutlet)','Pierogi ruskie','Kompot (fruit drink)','Żurek soup'],
    ARRAY['bar mleczny','milk bar','communist era poland','authentic warsaw','budget lunch warsaw','local experience','nostalgia poland','since 1957','old warsaw','cheap eats warsaw','working class lunch','traditional food','time travel poland','soviet era canteen'],
    'A surviving communist-era milk bar (bar mleczny) — a uniquely Polish institution. Open since 1957, unchanged. Incredibly cheap, filling, and authentic. Mostly patronised by Warsaw office workers and older locals. A true time-capsule experience. Closed on weekends.'
),
(
    '00000000-0000-0000-0000-000000000013',
    'E. Wedel Chocolate Lounge',
    'Historic 1851 chocolate brand''s elegant cafe — famous for thick hot drinking chocolate.',
    'ul. Szpitalna 8, 00-031 Warszawa',
    'Warsaw', 'Poland',
    52.2335, 21.0105,
    'Cafe', 'Desserts',
    'https://images.unsplash.com/photo-1542181961-9590d0c79dab?q=80&w=1000&auto=format&fit=crop',
    4.5, '$', '08:00 - 22:00',
    ARRAY['Chocolate','Historic','Desserts'],
    ARRAY['Since 1851','Warsaw Classic'],
    ARRAY['Romantic','Nostalgic','Elegant'],
    ARRAY['Historic','WiFi'],
    ARRAY['date','family','solo','anniversary'],
    ARRAY['vegetarian'],
    true, false, false, 0, false,
    'The "pianka" hot drinking chocolate is so thick you can stand a teaspoon in it — it''s the must-order item. Best on a rainy autumn or winter day for peak comfort.',
    ARRAY['Pianka na gorąco (thick hot chocolate)','Ptasie mleczko (Wedel marshmallow chocolate)','Ice cream sundae','Chocolate fondue'],
    ARRAY['hot chocolate warsaw','wedel chocolate','historic cafe warsaw','1851 brand','sweet tooth warsaw','romantic cafe','chocolate lover','dessert spot warsaw','tourist attraction','anniversary cafe','instagrammable','rainy day cafe','classic warsaw','gift shop chocolate'],
    'One of Warsaw''s most beloved institutions. E. Wedel is Poland''s most famous chocolate brand since 1851. The cafe is elegant but accessible. The pianka (hot drinking chocolate) is legendary. Great for dates, family treats, and anyone with a sweet tooth. Very photogenic interior.'
),
(
    '00000000-0000-0000-0000-000000000014',
    'Same Krafty',
    'Warsaw''s best craft beer bar in a vaulted brick cellar near Old Town with 20+ Polish taps.',
    'ul. Freta 4/6, 00-227 Warszawa',
    'Warsaw', 'Poland',
    52.2516, 21.0104,
    'Bar', 'Polish',
    'https://images.unsplash.com/photo-1538488881038-e252a119ace7?q=80&w=1000&auto=format&fit=crop',
    4.4, '$', '14:00 - 02:00',
    ARRAY['Craft Beer','Polish Brewery','Vaulted Bar'],
    ARRAY['20+ Craft Taps','Local Breweries'],
    ARRAY['Lively','Casual','Cozy'],
    ARRAY['Craft Beer','Outdoor Seating'],
    ARRAY['friends','groups','after work','party'],
    ARRAY['vegetarian options'],
    true, true, false, 0, false,
    'Ask the bartender for a 4-sample tasting flight — great way to explore Polish craft beer. The vaulted brick downstairs cellar is stunning in winter, while the terrace fills up in summer.',
    ARRAY['Craft beer tasting flight (4 pours)','Browar Artezan IPA','Chmielna Brewing sour ale','Craft beer of the month'],
    ARRAY['craft beer warsaw','polish craft beer','new town warsaw bar','vaulted bar warsaw','beer tasting','local brewery warsaw','pub crawl warsaw','nightlife warsaw','hip bar warsaw','friday night warsaw','trendy bar','near old town','beer flight','craft ale'],
    'The go-to spot for Polish craft beer in Warsaw. 20+ taps exclusively from Polish microbreweries. Beautiful vaulted brick interior. Near the Old Town and New Town area. Very popular Thu–Sat evenings. Great for beer lovers wanting to explore the booming Polish craft scene.'
),
(
    '00000000-0000-0000-0000-000000000015',
    'Pyzy Flaki Gorące',
    'Warsaw-style dumplings served in iconic glass jars — a beloved local institution.',
    'ul. Andersa 1, 00-159 Warszawa',
    'Warsaw', 'Poland',
    52.2424, 21.0036,
    'Restaurant', 'Polish',
    'https://images.unsplash.com/photo-1563245372-f21724e3856d?q=80&w=1000&auto=format&fit=crop',
    4.7, '$', '11:00 - 21:00',
    ARRAY['Pyzy','Warsaw Classic','Dumplings'],
    ARRAY['Warsaw Icon','Glass Jar Serving'],
    ARRAY['Casual','Local','Quirky'],
    ARRAY['Takeaway','Quick Service'],
    ARRAY['solo','lunch','friends','budget'],
    ARRAY['vegetarian options'],
    false, false, false, 0, false,
    'The glass jar presentation is iconic — photograph before eating. Pyzy are different from pierogi: thicker, softer potato dough. Order with extra caramelised onions and a side of bigos.',
    ARRAY['Pyzy (Warsaw dumplings in glass jar)','Flaki gorące (tripe soup)','Gołąbki (stuffed cabbage rolls)','Bigos (hunter''s stew)'],
    ARRAY['pyzy warsaw','warsaw dumplings','glass jar food','instagrammable food warsaw','authentic warsaw','polish street food warsaw','local food warsaw','cheap eats warsaw','traditional warsaw cuisine','unique food experience','best local food warsaw','comfort food poland','popular warsaw restaurant'],
    'A beloved Warsaw institution known for its unique pyzy (Warsaw-style potato dumplings) served in glass jars. Different from Krakow''s pierogi — thicker, softer. Very high ratings, always busy at lunch. One of the most authentic local food experiences in Warsaw. Affordable and filling.'
),
(
    '00000000-0000-0000-0000-000000000016',
    'Nolita Restaurant',
    'Michelin-starred contemporary European restaurant with an 8-course tasting menu.',
    'ul. Wilcza 46, 00-679 Warszawa',
    'Warsaw', 'Poland',
    52.2246, 21.0143,
    'Fine Dining', 'Contemporary European',
    'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1000&auto=format&fit=crop',
    4.7, '$$$$', '18:00 - 23:00',
    ARRAY['Michelin Star','Tasting Menu','Contemporary'],
    ARRAY['1 Michelin Star','Chef''s Table Available'],
    ARRAY['Elegant','Sophisticated','Romantic'],
    ARRAY['Tasting Menu','Wine Pairing','Chef''s Table'],
    ARRAY['anniversary','date','business','special occasion'],
    ARRAY['vegetarian accommodations on request'],
    false, false, true, 1, false,
    'Book 2–3 weeks ahead minimum. When booking, request the chef''s table (only 2 seats at the kitchen pass) — watching the kitchen in full flow is a dining experience in itself.',
    ARRAY['8-course seasonal tasting menu','Sommelier wine pairing','Seasonal fish dish with local herbs','Pre-dessert amuse-bouche'],
    ARRAY['michelin star warsaw','michelin 1 star','fine dining warsaw','tasting menu warsaw','chef''s table','anniversary dinner warsaw','special occasion warsaw','romantic dinner warsaw','best restaurant warsaw','upscale warsaw','contemporary european','wine pairing warsaw','luxury dining'],
    '1 Michelin star. One of the best restaurants in Warsaw. 8-course tasting menu using seasonal Polish ingredients with French technique. Intimate, elegant setting. The chef''s table experience is exceptional. Reservations essential — book 2-3 weeks ahead. Perfect for the most special occasions.'
)

on conflict (id) do nothing;
