-- Migration: Add KG Agent fields to cuisines, dishes, ingredients
-- These columns are generated by the KG AI Agent and were missing from the original schema

-- ── CUISINES ──────────────────────────────────────────────────────────────────
ALTER TABLE cuisines
    ADD COLUMN IF NOT EXISTS region          TEXT,
    ADD COLUMN IF NOT EXISTS aliases         TEXT[]   DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS typical_dishes  TEXT[]   DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS key_ingredients TEXT[]   DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS flavor_profile  TEXT;

-- ── DISHES ────────────────────────────────────────────────────────────────────
ALTER TABLE dishes
    ADD COLUMN IF NOT EXISTS cuisine_name       TEXT,
    ADD COLUMN IF NOT EXISTS preparation_style  TEXT,
    ADD COLUMN IF NOT EXISTS dietary_tags       TEXT[]   DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS flavor_notes       TEXT,
    ADD COLUMN IF NOT EXISTS best_pairing       TEXT;

-- ── INGREDIENTS ───────────────────────────────────────────────────────────────
ALTER TABLE ingredients
    ADD COLUMN IF NOT EXISTS description     TEXT,
    ADD COLUMN IF NOT EXISTS flavor_profile  TEXT,
    ADD COLUMN IF NOT EXISTS common_pairings TEXT[]   DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS dietary_info    TEXT[]   DEFAULT '{}';

-- Refresh PostgREST schema cache so new columns are immediately visible
NOTIFY pgrst, 'reload schema';
